# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ✅ Firebase requires static frameworks on React Native
$RNFirebaseAsStaticFramework = true

# ✅ Allow static linkage for Swift pods like Firebase
use_frameworks! :linkage => :static
target 'hygrometer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'LocationWhenInUse',
    'Camera',
    'Microphone',
    'PhotoLibrary',
    'BluetoothPeripheral',
    'Notifications'
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Allow non-modular includes
  #  installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  #       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  #     end
  #   end
  end
end
